services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317"        # OTLP gRPC receiver (for collector -> jaeger)
      - "4318"        # OTLP HTTP receiver (for telemetrygen -> jaeger)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-demo

  otel-collector:
    image: otelcontribcol:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./test-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - jaeger
    networks:
      - otel-demo
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4317"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # # Generate traces with large SQL statements to demonstrate compression
  # telemetrygen-large:
  #   image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
  #   container_name: telemetrygen-large
  #   command:       [
  #       "traces",
  #       "--otlp-insecure",
  #       "--otlp-endpoint=otel-collector:4317",
  #       "--traces=1",
  #       "--child-spans=3",
  #       "--otlp-attributes=k8s.namespace.name=\"my-namespace\"",
  #       "--otlp-attributes=k8s.deployment.name=\"my-deployment\"",
  #       "--otlp-attributes=k8s.replicaset.name=\"my-deployment-66cf4d99b5\"",
  #       "--otlp-attributes=k8s.pod.name=\"my-deployment-66cf4d99b5-kpqg\"",
  #       "--otlp-attributes=k8s.pod.uid=\"7293ca81-d35e-459d-b15a-a8197fbc03e4\"",
  #       "--otlp-attributes=k8s.node.name=\"my-node\"",
  #       "--otlp-attributes=cloud.availability.zone=\"my-az\"",
  #       "--otlp-attributes=cloud.region=\"my-region\"",
  #        "--otlp-attributes=db.statement=\"SELECT * FROM db.scheme\"",
  #     ]
  #   depends_on:
  #     - otel-collector
  #   networks:
  #     - otel-demo

networks:
  otel-demo:
    driver: bridge   